server:
  port: ${SPRING_APP_PORT}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    database: ${JPA_DATABASE}
    database-platform: ${JPA_DATABASE_PLATFORM}